spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6000/warehouse}
    username: ${SPRING_DATASOURCE_USERNAME:warehouse_user}
    password: ${SPRING_DATASOURCE_PASSWORD:warehouse_pass}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

external-services:
  predict-order-url: ${PREDICT_ORDER_URL:http://localhost:8081/predict/order}
  substitution-suggest-url: ${SUBSTITUTION_SERVICE_URL:http://localhost:8000/substitution/suggest}
  shortage-url: ${SHORTAGE_SERVICE_URL:http://localhost:8083/shortage/proactive-call}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:1234,http://127.0.0.1:1234}
